service: serverless-indexer
app: serverless-indexer-app
org: scissorsneedfoodtoo

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    ALGOLIA_ID: ${self:custom.awsSecrets.ALGOLIA_ID_${self:custom.currStage}}
    ALGOLIA_ADMIN_KEY: ${self:custom.awsSecrets.ALGOLIA_ADMIN_KEY_${self:custom.currStage}}

custom:
  stageMap:
    dev: DEV
    prod: PROD
  currStage: ${self:custom.stageMap.${self:provider.stage}}
  awsSecrets: ${ssm:/aws/reference/secretsmanager/serverless-indexer~true}

functions:
  addIndex:
    handler: handler.addIndex
    events:
      - http:
          path: add
          method: post

  deleteIndex:
    handler: handler.deleteIndex
    events:
      - http:
          path: delete
          method: post

  updateIndex:
    handler: handler.updateIndex
    events:
      - http:
          path: update
          method: post

plugins:
  - serverless-offline
