service: serverless-indexer
app: serverless-indexer-app
org: scissorsneedfoodtoo

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  environment:
    # ALGOLIA_ID: ${file(./.env.yml):ALGOLIA_ID}
    # ALGOLIA_ADMIN_KEY: ${file(./.env.yml):ALGOLIA_ADMIN_KEY}
    # ALGOLIA_ID: ${secrets:ALGOLIA_ID}
    # ALGOLIA_ADMIN_KEY: ${secrets:ALGOLIA_ADMIN_KEY}
    ALGOLIA_ID: ${self:custom.awsSecrets.ALGOLIA_ID}
    ALGOLIA_ADMIN_KEY: ${self:custom.awsSecrets.ALGOLIA_ADMIN_KEY}

custom:
  awsSecrets: ${ssm:/aws/reference/secretsmanager/serverless-indexer~true}

functions:
  addIndex:
    handler: handler.addIndex
    events:
      - http:
          path: add
          method: post

  deleteIndex:
    handler: handler.deleteIndex
    events:
      - http:
          path: delete
          method: post

  updateIndex:
    handler: handler.updateIndex
    events:
      - http:
          path: update
          method: post

plugins:
  - serverless-offline
